# Generated by Django 5.2.5 on 2025-08-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("match_date", models.DateField()),
                ("match_time", models.CharField(blank=True, max_length=10, null=True)),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                ("is_played", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "league_match",
                "ordering": ["week_number", "match_date", "match_time"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "league_player",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("points", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "league_team",
                "ordering": ["-points", "name"],
                "managed": False,
            },
        ),
    ]
