# Generated by Django 5.2.6 on 2025-09-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="players/"),
                ),
            ],
            options={
                "db_table": "league_player",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "league_team",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("match_date", models.DateField()),
                ("match_time", models.CharField(blank=True, max_length=10, null=True)),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                ("is_played", models.BooleanField(default=False)),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="league.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="league.team",
                    ),
                ),
                (
                    "mom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mom_awards",
                        to="league.player",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Matches",
                "db_table": "league_match",
                "ordering": ["week_number", "match_date", "match_time"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("own_goal", models.BooleanField(default=False)),
                ("goals", models.PositiveIntegerField(default=1)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="league.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="league.player"
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("YELLOW", "Yellow Card"), ("RED", "Red Card")],
                        max_length=6,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="league.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="league.player",
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="league.team",
            ),
        ),
        migrations.CreateModel(
            name="Team_Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("matches_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("goals_for", models.IntegerField(default=0)),
                ("goals_against", models.IntegerField(default=0)),
                ("goal_difference", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league.match",
                    ),
                ),
            ],
            options={
                "db_table": "league_team_standing",
                "ordering": ["-points", "name"],
                "managed": True,
            },
        ),
    ]
