# Generated by Django 5.2.5 on 2025-08-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={
                "managed": True,
                "ordering": ["week_number", "match_date", "match_time"],
                "verbose_name_plural": "Matches",
            },
        ),
    ]
