# Generated by Django 5.2.6 on 2025-09-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="is_walkover",
            field=models.BooleanField(default=False),
        ),
    ]
