# Generated by Django 5.2.5 on 2025-08-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0002_alter_match_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={
                "managed": False,
                "ordering": ["week_number", "match_date", "match_time"],
                "verbose_name_plural": "Matches",
            },
        ),
    ]
