# Generated by Django 5.2.6 on 2025-09-07 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0002_match_is_walkover"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="walkover_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="walkover_wins",
                to="league.team",
            ),
        ),
    ]
