# Generated by Django 5.2.6 on 2025-09-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0003_match_walkover_winner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A detailed description of the tournament."
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
    ]
