# Generated by Django 5.2.5 on 2025-08-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0003_alter_match_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"managed": True},
        ),
    ]
