# Generated by Django 5.2.6 on 2025-09-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0004_tournament"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="description",
        ),
        migrations.AddField(
            model_name="tournament",
            name="long_description",
            field=models.TextField(
                default="No description provided.",
                help_text="A detailed, long description of the tournament.",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="short_description",
            field=models.CharField(
                default="Untitled Tournament",
                help_text="A short description of the tournament.",
                max_length=255,
            ),
        ),
    ]
