# Generated by Django 5.2.5 on 2025-08-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0004_alter_player_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"managed": True, "ordering": ["-points", "name"]},
        ),
    ]
