# Generated by Django 5.2.6 on 2025-09-09 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0005_remove_tournament_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="league.tournament",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="league.tournament",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="league.tournament",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="league.tournament",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="league.tournament",
            ),
        ),
        migrations.AddField(
            model_name="team_standing",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standings",
                to="league.tournament",
            ),
        ),
    ]
