# Generated by Django 5.2.6 on 2025-09-10 03:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("league", "0006_card_tournament_goal_tournament_match_tournament_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="player_images"
            ),
        ),
    ]
