# Generated by Django 5.2.5 on 2025-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0006_team_draws_team_goal_difference_team_goals_against_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team_Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("matches_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("goals_for", models.IntegerField(default=0)),
                ("goals_against", models.IntegerField(default=0)),
                ("goal_difference", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "league_team_standing",
                "ordering": ["-points", "name"],
                "managed": True,
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"managed": False, "ordering": ["-points", "name"]},
        ),
    ]
