# Generated by Django 5.2.5 on 2025-08-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0007_team_standing_alter_team_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"managed": True, "ordering": ["-points", "name"]},
        ),
        migrations.AlterModelOptions(
            name="team_standing",
            options={"managed": False, "ordering": ["-points", "name"]},
        ),
    ]
