# Generated by Django 5.2.6 on 2025-09-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0007_alter_player_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamOfTheWeek",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("week_number", models.PositiveSmallIntegerField()),
                ("weekend_date", models.DateField()),
                (
                    "goal_keeper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_keeper_weeks",
                        to="league.player",
                    ),
                ),
                (
                    "left_defence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_defence_weeks",
                        to="league.player",
                    ),
                ),
                (
                    "left_mid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_mid_weeks",
                        to="league.player",
                    ),
                ),
                (
                    "right_defence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_defence_weeks",
                        to="league.player",
                    ),
                ),
                (
                    "right_mid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_mid_weeks",
                        to="league.player",
                    ),
                ),
                (
                    "striker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="striker_weeks",
                        to="league.player",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_of_the_weeks",
                        to="league.tournament",
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
    ]
