# Generated by Django 5.2.6 on 2025-09-24 04:59

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0008_teamoftheweek"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Name of the sponsor", max_length=30),
                ),
                (
                    "sponsor_type",
                    models.CharField(
                        help_text="Type of sponsor (max 30 characters)", max_length=30
                    ),
                ),
                (
                    "sponsor_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Sponsor image stored in Cloudinary",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the sponsor", null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location of sponsor",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address", max_length=254, null=True
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="Official website URL", null=True
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, help_text="Instagram profile URL", null=True
                    ),
                ),
                (
                    "linktree",
                    models.URLField(blank=True, help_text="Linktree URL", null=True),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        help_text="Tournament this sponsor belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="league.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsors",
                "ordering": ["id"],
                "managed": True,
            },
        ),
    ]
