# Generated by Django 5.2.5 on 2025-08-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0008_alter_team_options_alter_team_standing_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="draws",
        ),
        migrations.RemoveField(
            model_name="team",
            name="goal_difference",
        ),
        migrations.RemoveField(
            model_name="team",
            name="goals_against",
        ),
        migrations.RemoveField(
            model_name="team",
            name="goals_for",
        ),
        migrations.RemoveField(
            model_name="team",
            name="losses",
        ),
        migrations.RemoveField(
            model_name="team",
            name="matches_played",
        ),
        migrations.RemoveField(
            model_name="team",
            name="wins",
        ),
    ]
