# Generated by Django 5.2.6 on 2025-09-24 12:19

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0008_teamoftheweek"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("sponsor_type", models.CharField(max_length=30)),
                (
                    "sponsor_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Sponsor image stored in Cloudinary",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=60, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("instagram", models.CharField(blank=True, max_length=30, null=True)),
                ("linktree", models.URLField(blank=True, null=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="league.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "league_sponsor",
                "managed": True,
            },
        ),
    ]
