# Generated by Django 5.2.5 on 2025-08-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0009_remove_team_draws_remove_team_goal_difference_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"managed": True},
        ),
        migrations.RemoveField(
            model_name="team",
            name="points",
        ),
    ]
