# Generated by Django 5.2.6 on 2025-09-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0009_sponsor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="name",
            field=models.CharField(help_text="Name of the sponsor", max_length=80),
        ),
    ]
