# Generated by Django 5.2.6 on 2025-09-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0009_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournament_start_date",
            field=models.DateField(
                blank=True, help_text="The start date of the tournament.", null=True
            ),
        ),
    ]
