# Generated by Django 5.2.6 on 2025-10-02 09:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0010_tournament_tournament_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="logo_images"
            ),
        ),
    ]
