# Generated by Django 5.2.5 on 2025-08-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0010_alter_team_options_remove_team_points"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team_standing",
            options={"managed": True, "ordering": ["-points", "name"]},
        ),
    ]
