# Generated by Django 5.2.6 on 2025-09-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0010_alter_sponsor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Phone number", max_length=50, null=True
            ),
        ),
    ]
