# Generated by Django 5.2.6 on 2025-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0011_team_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
