# Generated by Django 5.2.6 on 2025-09-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0011_alter_sponsor_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsor",
            name="instagram",
            field=models.CharField(
                blank=True,
                help_text="Instagram handle or simple text",
                max_length=100,
                null=True,
            ),
        ),
    ]
