# Generated by Django 5.2.5 on 2025-08-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0011_alter_team_standing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"managed": True},
        ),
    ]
