# Generated by Django 5.2.5 on 2025-08-30 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0012_alter_player_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="player",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"managed": False},
        ),
        migrations.AddField(
            model_name="team_standing",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league.match",
            ),
        ),
    ]
