# Generated by Django 5.2.5 on 2025-09-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0013_alter_player_options_alter_team_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={
                "managed": True,
                "ordering": ["week_number", "match_date", "match_time"],
                "verbose_name_plural": "Matches",
            },
        ),
        migrations.AlterModelOptions(
            name="team_standing",
            options={"managed": False, "ordering": ["-points", "name"]},
        ),
    ]
