# Generated by Django 5.2.5 on 2025-09-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0014_alter_match_options_alter_team_standing_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="mom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mom_awards",
                to="league.player",
            ),
        ),
    ]
