# Generated by Django 5.2.5 on 2025-09-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0015_match_away_team_match_home_team_match_mom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={
                "managed": False,
                "ordering": ["week_number", "match_date", "match_time"],
                "verbose_name_plural": "Matches",
            },
        ),
        migrations.CreateModel(
            name="CARD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[("YELLOW", "Yellow Card"), ("RED", "Red Card")],
                        max_length=6,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="league.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="league.player",
                    ),
                ),
            ],
        ),
    ]
