# Generated by Django 5.2.5 on 2025-09-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0017_alter_card_options_goal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={"managed": True},
        ),
        migrations.AddField(
            model_name="goal",
            name="goals",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
