# Generated by Django 5.2.5 on 2025-09-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_alter_goal_options_goal_goals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': True},
        ),
    ]
