# Generated by Django 5.2.5 on 2025-09-03 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_player_image_player_team'),
    ]

   
